int_columns = [
    "Labor_force",
    "Waterways",
    "HIV_AIDS_people_living_with_HIV_AIDS",
    "HIV_AIDS_deaths",
    "Telephones_main_lines_in_use",
    "Internet_users",
    "Area",
    "Natural_gas_production",
    "Roadways",
    "Railways",
    "Natural_gas_exports",
    "Natural_gas_imports",
    "Natural_gas_consumption",
    "Oil_production",
    "Electricity_production"]

float_columns = [
    "Land_use",
    "Land_boundaries",
    "Infant_mortality_rate",
    "Inflation_rate_consumer_prices",
    "HIV_AIDS_adult_prevalence_rate",
    "Sex_ratio",
    "Television_broadcast_stations",
    "Age_structure",
    "Radio_broadcast_stations",
    "Irrigated_land",
    "Coastline",
    "Languages",
    "Heliports",
    "GDP_real_growth_rate",
    "Population_growth_rate",
    "Unemployment_rate",
    "Total_fertility_rate",
    "Industrial_production_growth_rate",
    "Suffrage",
    "Airports_with_paved_runways",
    "Airports_with_unpaved_runways",
    "Military_expenditures",
    "Median_age",
    "Distribution_of_family_income_Gini_index",
    "Manpower_reaching_militarily_significant_age_annually",
    "Imports_partners",
    "GDP_composition_by_sector",
    "Electricity_exports",
    "Labor_force_by_occupation",
    "Commercial_bank_prime_lending_rate",
    "Pipelines",
    "Death_rate",
    "Total_renewable_water_resources",
    "Freshwater_withdrawal_domestic_industrial_agricultural",
    "Birth_rate",
    "Education_expenditures",
    "Exchange_rates",
    "Ethnic_groups",
    "Exports_partners",
    "School_life_expectancy_primary_to_tertiary_education",
    "Population_below_poverty_line",
    "Household_income_or_consumption_by_percentage_share",
    "Net_migration_rate",
    "Religions",
    "Electricity_imports",
    "Urbanization",
    "Manpower_fit_for_military_service",
    "Elevation_extremes",
    "Literacy",
    "Life_expectancy_at_birth",
    "Maritime_claims",
    "Manpower_available_for_military_service"]

dollar_columns = [
    "GDP_per_capita_PPP",
    "GDP_purchasing_power_parity",
    "Imports",
    "Stock_of_direct_foreign_investment_abroad",
    "Stock_of_direct_foreign_investment_at_home",
    "GDP_official_exchange_rate",
    "Market_value_of_publicly_traded_shares",
    "Exports",
    "Debt_external",
    "Budget",
    "Current_account_balance",
    "Stock_of_domestic_credit",
    "Oil_exports",
    "Oil_consumption",
    "Oil_imports",
    "Oil_proved_reserves",
    "Natural_gas_proved_reserves",
    "Airports",
    "Electricity_consumption",
    "Population",
    "Telephones_mobile_cellular",
    "Public_debt",
    "Investment_gross_fixed",
    "Internet_hosts",
    "Reserves_of_foreign_exchange_and_gold",
    "Military_service_age_and_obligation",
    "Merchant_marine"]

not_nations = [
    "United States Pacific Island Wildlife Refuges",
    "Ashmore and Cartier Islands",
    "Atlantic Ocean",
    "Pacific Ocean",
    "Jan Mayen",
    "Southern Ocean",
    "Heard Island and McDonald Islands",
    "Coral Sea Islands",
    "South Georgia and the South Sandwich Islands",
    "Error in running event chain: "
    "Error occurred while trying to run the event chain.",
    "Indian Ocean",
    "Navassa Island",
    "Spratly Islands",
    "Netherlands Antilles",
    "Paracel Islands",
    "Wake Island",
    "Bouvet Island",
    "Clipperton Island",
    "Mayotte",
    "British Indian Ocean Territory",
    "Arctic Ocean",
    "French Southern and Antarctic Lands",
    "Antarctica"]
